[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for HTML and SSR pages
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Ensure clean builds
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  
# Clear the Netlify cache before building - run this command when needed
# [plugins.inputs]
#   postBuild = "curl -X POST -d {} https://api.netlify.com/build_hooks/YOUR_BUILD_HOOK_ID?clear_cache=true"